#%RAML 1.0
title: Test API
baseUri: https://test.maqdev.com
types:
  BookTag:
    enum: [new,best-seller,classics]

  BookProperties:
    type: object
    properties:
      publishYear:
        type: number
        format: int16
      sold: integer
      issn: string
      tag: BookTag

  Book:
    type: object
    properties:
      bookId: string
      authorId: string
      bookName: string
      authorName: string
      bookProperties: BookProperties

  BookTransaction:
    type: object
    properties:
      transactionId: string

  BookCreatedTransaction:
    type: object
    properties:
      transactionId: string

  Click:
    type: object
    properties:
      clickUrl: string

  ClickConfirmation:
    type: object
    properties:
      id: string

  ClicksInformation:
    type: object
    properties:
      count:
        type: number
        format: long
      lastRegistered:
        type: datetime
        required: false
      firstInserted?: datetime

  Author:
    type: object
    properties:
      name: string
      books:
        type: Book[]

/authors/{authorId}/books/{bookId}:
  uriParameters:
    authorId: string
    bookId: string
  get:
    responses:
      200:
        body:
          application/json:
            type: Book
  put:
    body:
      application/json:
        type: Book
    responses:
      200:
      201:

/authors/{authorId}/books:
  uriParameters:
    authorId: string
  get:
    responses:
      200:
  post:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
            type: BookTransaction
      201:
        body:
          application/json:
            type: BookCreatedTransaction

/clicks:
  post:
    body:
      application/json:
        type: Click
    responses:
      201:
        body:
          application/json:
            type: ClickConfirmation

/clicks/{clickUrl}:
  uriParameters:
    clickUrl: string
  get:
    body:
      application/json:
        type: ClicksInformation
